### PR TITLE
Fix: station availability should be a purchase callback

### PR DESCRIPTION
**Pull request by ahyangyi**

### CODE REVIEW

**Comment by ldpl** [comment]
are you sure about this? nml seems to have it as a default 
https://github.com/OpenTTD/nml/blob/a139540406bdae9281e43277d8f435a0b362bd39/nml/actions/action3_callbacks.py#L141

**Comment by ldpl** [comment]
I tried to test it but couldn't get it working either way xD

**Comment by ahyangyi** [comment]
I remember that I had to make it a purchase callback to get it working. But I want to take some time to test it again, considering that NML also does it the other way.

**Comment by ahyangyi** [comment]
Hi,

I tested it again, and can confirm that it needs to be a purchase callback to work.

Also, I have implemented a "starting year" feature in my station set [2 months ago](https://github.com/ahyangyi/openttd-newgrfs/releases/tag/station-0.2.2), it might serve as an example.

Admittedly my station set takes forever to rebuild (not grf-py's fault, gorender doesn't like huge models). But if you want to replicate my experiments you can comment out the huge 2018 station [here](https://github.com/ahyangyi/openttd-newgrfs/blob/main/station/dovemere_gen.py) and use the small 1934 station to test the feature.

Alternatively, just trust my words XD

And perhaps we should also file a bug to nml.

**Comment by ldpl** [comment]
Don't have time to check this myself so I'll just merge it. Can always change again if something new is discovered xD

**Pull request merged**
